data=read.table("electricity.txt",sep=";",header=TRUE)
TIMES=paste(data[,"Date"],data[,"Time"])
times=gsub("1/","01/",TIMES)
TIMES=gsub("2/","02/",times)
TIMES=strptime(TIMES,format="%d/%m/%Y %H:%M:%S")
data[,"Date"]=NULL
data[,"Time"]=NULL
data=cbind(TIMES,data)
png(filename="plot1.png")
hist(data$Global_active_power,main="Global Active Power",xlab="Global Active Power (Kilowatts)",ylab="Frequency",col="RED")
dev.off()
png(filename="plot2.png")
plot(data$TIME,data$Global_active_power,type="l",ylab="Global Active Power (Kilowatts)",xlab="")
dev.off()

png(filename="plot3.png")
plot(data$TIME,data$Sub_metering_1,type="l",ylab="Energy sub metering",xlab="")
lines(data$TIME,data$Sub_metering_2,col="red")
lines(data$TIME,data$Sub_metering_3,col="blue")
legend("topright",lty=1,col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
dev.off()

png(filename="plot4.png")
par(mfrow=c(2,2))
plot(data$TIME,data$Global_active_power,type="l",ylab="Global Active Power",xlab="")
plot(data$TIME,data$Voltage,type="l",ylab="Voltage",xlab="datetime")
plot(data$TIME,data$Sub_metering_1,type="l",ylab="Energy sub metering",xlab="")
lines(data$TIME,data$Sub_metering_2,col="red")
lines(data$TIME,data$Sub_metering_3,col="blue")
legend("topright",lty=1,col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
plot(data$TIME,data$Global_reactive_power,type="l",ylab="Global_reactive_power",xlab="datetime")
dev.off()
